@echo off
echo Starting containers...
docker-compose up --build

echo Waiting for services to start...
timeout /t 5 /nobreak

echo Opening browser...
start http://localhost:8080

echo Showing logs...
docker-compose logs -f 